version: '3.9'

services:

  auth:
    build:
      context: ./auth
    ports:
      - "8082:8082"
    expose:
      - 50051
    depends_on:
      mysql:
        condition: service_healthy
    command: ["/app/main"]
    networks:
      - auth-network
      - grpc-network

  core:
    build:
      context: ./core
    container_name: core
    ports:
      - "8080:8080"

    environment:
      AUTH_GRPC_ADDRESS: auth
      AUTH_GRPC_PORT: 50051
      
      PROJECT_DATASOURCE_JDBC_URL: jdbc:postgresql://postgresql:5432/core
      PROJECT_DATASOURCE_USERNAME: postgres
      PROJECT_DATASOURCE_PASS: postgres

      ACTIVEMQ_URL: tcp://activemq:61616
      ACTIVEMQ_USERNAME: root
      ACTIVEMQ_PASSWORD: root

      AUTH_SERVICE_URL: auth:50051

    depends_on:
      - postgres
      - activemq

    networks:
      - core-network
      - grpc-network
      - mq-network

  postgres:
    image: postgres:13.13-bullseye
    container_name: postgresql

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core

    volumes:
      - postgres_db:/var/lib/postgresql/data

    networks:
      - core-network

  mysql:
    image: mysql:latest
    container_name: mysql

    environment:
      MYSQL_DATABASE: mysql
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - auth-network

  activemq:
    image: webcenter/activemq
    container_name: activemq

    ports:
      - "61616:61616"

    networks:
      - mq-network

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    command: [ "/app/main" ]
    networks:
      - auth-network

volumes:
  postgres_db:
  mysql_db:

networks:
  core-network:
  auth-network:
  grpc-network:
  mq-network: