apiVersion: v1
kind: Secret
metadata:
  name: core-secret
  namespace: core
stringData:
  PROJECT_DATASOURCE_USERNAME: postgres
  PROJECT_DATASOURCE_PASS: postgres

  ACTIVEMQ_USERNAME: root
  ACTIVEMQ_PASSWORD: root

