apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: auth
stringData:
  DB_DRIVER: mysql
  DB_SOURCE: root:12345678@tcp(mysql-clusterip-srv:3306)/auth?charset=utf8mb4&parseTime=True&loc=Local